### ISSUE TITLE
gammacorrect stretching

### ISSUE THREAD

**Issue by technomancy** [meric/renderplanet#3]
When I adapted the renderplanet code to my game I was seeing some strange stretching effect. I was able to reproduce the problem in the renderplanet codebase by adding `function love.conf(t) t.gammacorrect = true end` to `conf.lua`.

Any idea what's going wrong? I have a very old graphics card (Intel integrated from 2008) so it could just be that. I don't mind turning off gammacorrect, but I'm curious if anyone else is seeing this or knows of a better fix.

**Comment by technomancy** [comment]
Oops; forgot to attach the screenshot:
![stretched-earth](https://user-images.githubusercontent.com/141/33001962-fd5c1b32-cd65-11e7-923c-dc8312c24bd9.png)

**Comment by meric** [comment]
https://love2d.org/wiki/love.graphics.isGammaCorrect It looks like gamma
correct converts the values of the colours that are sent into shaders. Since the
map projection coordinates (e.g. lat/long) are mapped to colours on the
texture, you see the warping effect - you'll have to change the math to
calculate which colour correspond to which coordinate if you turn on gamma
correct. :(

**Comment by technomancy** [comment]
Thanks; that makes a lot of sense. In my case adding `{linear=true}` to the second arg of `newImage` did the trick!
